import {
  AUTH_ACCESS_EXPIRES_IN,
  AUTH_ACCESS_SECRET,
  AUTH_REFRESH_EXPIRES_IN,
  AUTH_REFRESH_SECRET,
  AUTH_PASSWORD_SALTING_ROUNDS,
  AUTH_PHONE_CONFIRMATION_CODE_LENGTH,
  AUTH_PHONE_CONFIRMATION_CODE_EXPIRES_IN,
} from '@/configs/env';

export const authConfig = {
  refresh: { expiresIn: AUTH_REFRESH_EXPIRES_IN, secret: AUTH_REFRESH_SECRET },
  access: { expiresIn: AUTH_ACCESS_EXPIRES_IN, secret: AUTH_ACCESS_SECRET },
  passwordSaltingRounds: AUTH_PASSWORD_SALTING_ROUNDS,
  phoneConfirmationCodeLength: AUTH_PHONE_CONFIRMATION_CODE_LENGTH,
  phoneConfirmationCodeExpiresIn: AUTH_PHONE_CONFIRMATION_CODE_EXPIRES_IN,
};
