import {
  PRODUCTS_CART_SIZE_LIMIT,
  PRODUCTS_DISCOUNT_POLICY,
  PRODUCTS_FREE_SHIPPING_THRESHOLD,
  PRODUCTS_SHIPPING_PRICE,
} from '@/configs/env';

export const productsConfig = {
  shippingPrice: PRODUCTS_SHIPPING_PRICE,
  freeShippingThreshold: PRODUCTS_FREE_SHIPPING_THRESHOLD,
  cartSizeLimit: PRODUCTS_CART_SIZE_LIMIT,
  discountPolicy: PRODUCTS_DISCOUNT_POLICY,
};
